apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.labels.app }}
    module: {{ .Values.labels.module }}
  name: {{ .Values.containers.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      module: {{ .Values.labels.module }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        module: {{ .Values.labels.module }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.containers.name }}
        ports:
        - containerPort: {{ .Values.service.port }}
