apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.containers.name }}
  namespace: {{ .Values.containers.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: {{ .Values.service.port }}
