apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ .Values.labels.app }}
    module:  {{ .Values.labels.module }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
    module: {{ .Values.labels.module }}
status:
  loadBalancer: {}
